### ISSUE TITLE
[Bug Probably] build failure : doubt

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/TestImages.jl#104]
@johnnychen94 Not entirely about this but none of the TIF testimages are being shown on the website.But if this is intentional and how it's supposed to be,it still doesn't look good :sweat_smile: .Can you check?

**Comment by johnnychen94** [comment]
It looks good to me, e.g., the `cameraman` image is displayed normally. There are some special images (e.g., `hela-cells.tif`) with small values so it might look like a black image but it actually isn't.

```julia
julia> img = load("images/hela-cells.tif");

julia> extrema(channelview(img))
(0.0N0f16, 0.06249N0f16)
```
