### ISSUE TITLE
Issue with Project.toml on branch gh-pages

### ISSUE THREAD

**Issue by shak360** [JuliaImages/TestImages.jl#108]
Hi I'm having trouble running the `julia build.jl` command in the fourth step of the [contribution](https://testimages.juliaimages.org) (I'm trying to add an image for one of my personal projects).

Basically, after reading through some documentation, I've been able to distill it to the fact that the [Project.toml on the `gh-pages`](https://github.com/JuliaImages/TestImages.jl/blob/gh-pages/Project.toml) branch **only** has a `[deps]` set of lines, but lacks attributes for `name`, `uuid`, and `version` but the [Project.toml on the `master`](https://github.com/JuliaImages/TestImages.jl/blob/master/Project.toml) branch has all of these written. Is there a reason for the discrepancy?

**Comment by shak360** [comment]
The issue arises when I try to install packages on the `gh-pages` branch and Julia looks for the name on the Project.toml file and errors out.

I can easily fix this by going back to `master`, and then doing `import Pkg; Pkg.add("Images")` but I was just wondering why there's a discrepancy between the Project.toml files between the two branches.

**Comment by johnnychen94** [comment]
> Now I see that the branch gh-pages isn't really a "package" in the same way that the master branch of 'TestImages.jl` is

:+1: Yes it's only meant to tell Julia's Pkg what to do with `>pkg instantiate` and `>pkg up`. Users of `TestImages.jl` are not affected by this file at all.
