### ISSUE TITLE
improve the document page

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/TestImages.jl#128]
For this repository, images are deliberately separated from the source codes. This enables us to update TestImages codes without shipping the entire images folder in `gh-pages` branch. Julia package and storage system only [archive the branch where you trigger the registration](https://github.com/JuliaPackaging/PkgServer.jl/blob/b32969b8f44be9cb94a37cb62499131b466ff638/bin/gen_static.jl#L91-L92). Thus every release of TestImages itself only ships a very small amount of data. For example, the [v1.6.0 tarball](https://us-east.storage.julialang.org/package/5e47fb64-e119-507b-a336-dd2b206d9990/259804ebdbc5757ee1bee77860fa6070f9d7db62) is only 9Kb.

Currently, the document for this page uses some hard-to-read raw HTML (`index.html` in the `gh-pages`), so we'd like to improve it use markdown format.

There are three options:

1. Add `docs/` folder to the `master` branch and deploy Documenter.jl
2. deploy to the juliaimages.org
3. Rewrite with markdown and let github pages do the rendering with Jekyll.

The first two options allow us to use Documenter.jl, the third should be the simplest version. All require some rewrite here to support the thumbnail gallery.

**Comment by hyrodium** [comment]
Thanks for the detailed description!

I'm now trying to rewrite the documentation with Documenter.jl.

![testimages_documenter](https://user-images.githubusercontent.com/7488140/128618663-ea1c1673-3771-4043-9aae-fa0be3c418b4.gif)

Is this looks good?

If this is ok, I can make a PR.

**Comment by johnnychen94** [comment]
Definitely good!

**Comment by johnnychen94** [comment]
I now realize that maybe we can also add `docs/` to the `gh-pages` branch. By doing this we just need to remove the `deploydocs` line

**Comment by hyrodium** [comment]
I thought the fourth option is not usual way. Is there any pros for adding `docs` to `gh-pages`?
If we remove `depolydocs`, then we will lose versioned documentation.

**Comment by johnnychen94** [comment]
I don't have any preference here so anything that works I'm happy to get it in.

**Comment by hyrodium** [comment]
Ah, I didn't understand the purpose of `gh-pages` and `build.jl` enough. (Documenter.jl may overwrite the `gh-pages` branch.)

## Proposal
After thinking about it for a while, I came to the conclusion that it would be better to add a new branch `images` to this repository.

* `master` : This branch includes source code of TestImages.jl and source of documentation.
* `gh-pages` : All files in this branch will be automatically generated by Documenter.jl.
* `images` :  This branch contains images in the artifact.

### File organization
#### `master`
```
├── .github
│   └── workflows
│       ├── backport.yml
│       ├── CompatHelper.yml
│       ├── TagBot.yml
│       └── UnitTest.yml
├── .gitignore
├── Artifacts.toml
├── docs
│   ├── build (gitignored)
│   ├── make.jl (create some file in docs/src with TestImages.jl, generate docs, deploy to gh-pages)
│   ├── Manifest.toml (gitignored)
│   ├── Project.toml
│   └── src
│       ├── contributing.md
│       ├── imagelist.md (automatically generated with make.jl, and gitignored)
│       ├── index.md
│       ├── images (automatically generated with make.jl, and gitignored)
│               └── foo.png (automatically generated with make.jl, and gitignored)
│       └── thumbnails (automatically generated with make.jl, and gitignored)
│               └── foo.png (automatically generated with make.jl, and gitignored)
├── LICENSE
├── Project.toml
├── README.md
├── src
│   └── TestImages.jl
└── test
```

#### `gh-pages`

```
├── index.html
├── dev
├── stable -> v*
├── v*
└── versions.js
```

#### `images`
```
├── .github
│   └── workflows
│       └── upload_artifacts.yml
├── images
│   └── foo.png (contributers will add images to this directory)
├── metadata.yml (contributers may update this file)
├── build_artifacts.jl
└── Project.toml
```

Do you have any comments on this proposal?

**Comment by johnnychen94** [comment]
> Ah, I didn't understand the purpose of gh-pages and build.jl enough. (Documenter.jl may overwrite the gh-pages branch. Or, Documenter.jl may not expect other files to be in gh-pages branch.)

😄  I thought you already knows this when you said "I thought the fourth option is not usual way. Is there any pros for adding docs to gh-pages?"

Documenter.jl only override the existing files, so it's kind of not a problem for now. But it might be broken or cause confusion in the future. Moving images to another branch is definitely a better option.

LGTM, just one small thing:

`Manifest.toml` is deliberately committed into `images` to make sure [`build_artifacts.jl` works](https://github.com/JuliaImages/TestImages.jl/blob/d79a8c87de870bc9c98c463d240a0227fa9891fc/.github/workflows/upload_artifacts.yml#L26-L30). For this specific application, we can just lock the versions by committing a `Manifest.toml`.

**Comment by hyrodium** [comment]
>I thought you already knows ...

I'm new to `Artifacts.toml`, so I might make a mistake than usual... :sweat_smile: :pray:

>LGTM, just one small thing:
Manifest.toml is deliberate ...

Thanks for the comment! I got it.
I'll separate this into two PR:

1. Move images and related files to new `images` branch.
2. Add documentation with Documenter.jl.

**Comment by hyrodium** [comment]
I've removed some files from `gh-pages` branch and push them to `images` branch:
https://github.com/JuliaImages/TestImages.jl/tree/images

The current file organization in `images` branch:
```
├── .github
│   └── workflows
│       └── upload_artifacts.yml
├── images
│   └── foo.png (contributers will add images to this directory)
├── metadata.yml (contributers may update this file)
├── build_artifacts.jl
├── Manifest.toml
└── Project.toml
```

I'd like to include `metadata.yml` to `images` directory to be contained to artifacts:
```
├── .github
│   └── workflows
│       └── upload_artifacts.yml
├── images
│   ├── metadata.yml (contributers may update this file)
│   └── foo.png (contributers will add images to this directory)
├── build_artifacts.jl
├── Manifest.toml
└── Project.toml
```

If we change the file organization like this, we can:
* Include `metadata.yml` in `images.tar.gz`.
* Generate docs with metadata.
* Add function `Images.metadata(filename)` to get its metadata.

Is this sounds good?

**Comment by johnnychen94** [comment]
> I'd like to include metadata.yml to images directory to be contained to artifacts

Looks okay to me as long as we clearly document the contributor guideline.

> Add function `Images.metadata(filename)` to get its metadata.

Do you mean a non-exported function `TestImages.metadata(filename)`? If so we might also want to switch to use the toml format, it might be:

```toml
[[images]]
name="airplaneF16"
fullname = "Airplane (F-16)"
url = "http://sipi.usc.edu/database/download.php?vol=misc&img=4.2.05"
author = "USC-SIPI Image Database"

[[images]]
name = "autumn_leaves"
fullname =  "Autum Leaves"
url = "http://www.imagemagick.org/Usage/images/autumn_leaves.png"
```

using toml because TOML is a Julia standard library, and this file can be easily read as `Dict` by calling `TOML.parsefile`.

**Comment by johnnychen94** [comment]
Generating docs with metadata sounds good to me. What entry do you plan to let `metadata` support? I'm thinking of a subset of the following, but it really depends on how you choose to design the docs.

- "name"
- "size"
- "colorant"
- "fullname"
- "url"
- "author"
- "license"

**Comment by hyrodium** [comment]
I was just trying to changing the place of `metadata.yml` to fill the `Note` section below like in the [current documentation](https://testimages.juliaimages.org/):

![image](https://user-images.githubusercontent.com/7488140/128815731-772c7c50-cf9b-4ddc-8b6f-005417405e1b.png)

> Do you mean a non-exported function TestImages.metadata(filename)?

> What entry do you plan to let metadata support?

Sorry, I just thought that adding `TestImages.metadata` function would be one advantage, but I hadn't thought about the detailed specification.

>but it really depends on how you choose to design the docs

I think there's not much space in the `Note` section, so it might be hard to add more infomation than current documentation.

I'd like to keep the next PR to be small, so I will stop filling the `Note` section for now.
After the PR being merged, I can make a PR to change the `metadata.yml`.
