### ISSUE TITLE
Links not working in Documentation

### ISSUE THREAD

**Issue by kellertuer** [JuliaImages/TestImages.jl#40]
I noticed, that in the documentation, the links are not working. For example`lake` links to

[https://testimages.juliaimages.org/images/lake.png](https://testimages.juliaimages.org/images/lake.png)
but there is no image available at that URL
![https://testimages.juliaimages.org/images/lake.png](https://testimages.juliaimages.org/images/lake.png)

But I the thumbnails seem to exist. I can't check much further, because ImageDistances is broken atm (I saw, that the fix is already submitted to registry). So any tipp would be nice. Also 

If that's working again, I aim to provide the color version of lake ( http://sipi.usc.edu/database/database.php?volume=misc&image=12#top ). Should I then rename `lake` to `lake_gray`?

And finally – what about image rights? I know for the older test images, like lake, nobody cared, but how should this package handle that in general (i.e. if possible) to mention authors of images?

**Comment by timholy** [comment]
My understanding of various web-technologies is a bit shaky. You can select the `gh-pages` from the "branch" dropdown on the main page, perhaps that's where the links are defined? But if there is one master setting that controls this, I'd rather fix that.

I wonder if this is a consequence of the CNAME change? CC @ViralBShah.

**Comment by timholy** [comment]
WRT license, yes, we've tried to be careful, and in some cases I have emails from the original source owners (e.g., the Fabio image) granting permission. Attributions would be very helpful!

**Comment by kellertuer** [comment]
In the `gh-pages` branch, the link is still to the page of https://testimages.juliaimages.org (so that's the rendered one, right?), where the wrong links are. I also think it's the master's setting, I just could not find the correct one (otherwise I would've done a PR).

Concerning Attribution – yes, I think that would be good. Maybe – to the best of our knowledge – provide a source link and an author (if known)?

**Comment by timholy** [comment]
That would be good. At least initially this package downloaded each time from the original source, but that changed when we got the fancy web page. Some attributions can be found here: https://github.com/JuliaImages/TestImages.jl/commit/9db10e91143ce26a7acd7d1038e9c820e8f41154

Would be great to have help with this!

**Comment by kellertuer** [comment]
Ah I see. I'd love to help, I just have to get my head around, how the page is created, since I am working mostly with Documenter.jl currently.

**Comment by ViralBShah** [comment]
I am responsible for some of this - and please let me know how I can help.

**Comment by ViralBShah** [comment]
I see that there is a thumbnail for `lake.png` but the actual image is a `lake.tif`.

**Comment by ViralBShah** [comment]
May I suggest that rather than serve the website as `testimages.juliaimages.org`, why not just make it a sub-directory of the main `juliaimages.org` website? It will be significantly easy to maintain.

**Comment by ViralBShah** [comment]
f438eaa879068438cbe39ffedd52b3b60a743399 fixes the rendering issue.
