### ISSUE TITLE
Using build.jl on Julia 1.1

### ISSUE THREAD

**Issue by kellertuer** [JuliaImages/TestImages.jl#41]
I am still trying to get a first image submitted (`lake` in color), but I am struggling to get `build.jl` running on Julia 1.1 in order to PR the image its thumbnail and the updated gh-page.

while clearly (lines 4 and 38) `readline(f)` is now `read(f,String)` and I added a line 18 `global content` to not introduce a local variable, I am struggling with the last line of the `for` loop:

for the variable `img.properties` [here](https://github.com/JuliaImages/TestImages.jl/blob/39d12ab3982dc47e01cd7ecf3972e71eff8c4633/build.jl#L32) I can't find the proper replacement/update/fix, since I haven't worked with `Images.jl` much yet. Since `img` is an array of pixels, this `.properties` field does not exist.

How can I fix that?

**Comment by kellertuer** [comment]
I also haven't completely understood, why the `build.jl` generated both html and javascript and the javascript then generates a static homepage – one could also directly just provide a static html file.

Maybe I'll propose an update, that allows to further enhance entries for images on the page.

I would like to display the colorspace - however - still ;)

**Comment by timholy** [comment]
Oh wow, that is ancient code. Clearly predates Images 0.6, and we're at Images 0.18 now!

Try replacing `img.properties["colorspace"]` with something like `string(base_color_type(eltype(img)))`. You may have to say `using ColorTypes` for that to work.

**Comment by kellertuer** [comment]
Thanks, I got that running and a prototype to handle further metadata (authors and urls for now) using a `yml` file. My idea works fine on the first files but then I get a missing `OMETIFF` and when I try to add that

```
ERROR: Unsatisfiable requirements detected for package OMETIFF [2d0ec36b]:
 OMETIFF [2d0ec36b] log:
 ├─possible versions are: [0.0.1, 0.1.0-0.1.2, 0.2.0-0.2.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1, 0.1.0-0.1.2, 0.2.0-0.2.1]
 ├─restricted by compatibility requirements with Images [916415d5] to versions: [0.0.1, 0.1.0-0.1.1] or uninstalled, leaving only versions: [0.0.1, 0.1.0-0.1.1]
 │ └─Images [916415d5] log:
 │   ├─possible versions are: [0.2.0-0.2.50, 0.3.0-0.3.3, 0.4.0-0.4.50, 0.5.0-0.5.14, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0-0.9.1, 0.10.0-0.10.1, 0.11.0-0.11.5, 0.12.0, 0.13.0, 0.14.0, 0.15.0-0.15.1, 0.16.0-0.16.1, 0.17.0-0.17.3, 0.18.0] or uninstalled
 │   └─restricted to versions 0.18.0 by an explicit requirement, leaving only versions 0.18.0
 └─restricted by julia compatibility requirements to versions: 0.2.0-0.2.1 or uninstalled — no versions left
```

I also improved the HTML a little, will update the publish procedure then and will do a PR if everything works.

**Comment by kellertuer** [comment]
I created a PR with my proposal for metadata (and I worked a little on the HTML to use paragraphs instead of `h5`s and a definition list for the metdatata, see #42.

**Comment by kellertuer** [comment]
I finished the rework, since I got the build script finally working locally.
