### ISSUE TITLE
Restrict file names and check for already created thumbnails?

### ISSUE THREAD

**Issue by kellertuer** [JuliaImages/TestImages.jl#43]
When I did my rework for the metadata I noticed two small things

1) Recreating the thumbnails by calling `build.jl` deletes all old thumbnails, recreates them and hence one has to check them in again(?) or maybe I just did that and that's not meant to be? For the size of the repository it would be beneficial if only non existing one would be created. One then could still "trigger" recreation of a certain thumbnail by deleting the old one manually. That way only really _new_ thumbnails would enter a commit.

2) I am on a Mac and noticed that the `build.jl` script tried to open the file `.DS_Store` (Mac OSes _love_ to create that in many folders). Deleting the `.DS_Store` certainly solved that, but maybe filtering all files by ending would also be a good idea, i.e. create thumbnails only for a certain set of image types? Or maybe that is too restrictive?

**Comment by timholy** [comment]
Those are really good observations! I don't think this file has gotten much in the way of support from anyone since it was first created (see `git log build.jl`). These sound like excellent things to change.

**Comment by kellertuer** [comment]
I will try to implement an “image extension whitelist” then and a check to only recreate a thumbnail if it's nonexistent and document that accordingly.

**Comment by timholy** [comment]
Fixed by #47
