### ISSUE TITLE
Adding a 3D image and a 3D Point Spread Function

### ISSUE THREAD

**Issue by roflmaostc** [JuliaImages/TestImages.jl#90]
Hey,

I was wondering whether I could add another 3D image and a 3D point spread function (PSF) to the module?

I'm referring to this [image](https://github.com/roflmaostc/DeconvOptim.jl/blob/master/examples/obj.tif) and this [PSF](https://github.com/roflmaostc/DeconvOptim.jl/blob/master/examples/psf.tif).

For me it would be very helpful!

Thanks,

Felix

**Comment by timholy** [comment]
The image seems like it would be fine. Is the PSF anything more than a Gaussian? If so, `ImageFiltering.Kernel.gaussian` can generate that programmatically. I'd also be tempted to have the coordinates be symmetric around zero, i.e., `axes(psf) == (-21:21, -21:21, -21:21)` or something.

**Comment by roflmaostc** [comment]
The PSF is a simple 3D PSF of a microscope (not sure how sophisticated it is; I took it from the author and have the confirmation to use it). 
But the 2D cross section is rather a jinc ($J_1(x)/x$) function. At the moment it is centered in a way that FFT would take it natively.

But sure, I could fftshift it to the center.

**Comment by timholy** [comment]
If it's not easy to generate programmatically then I could support having it here.

It's not `fftshifting` I'm asking for: I'm suggesting it should be loaded from disk with symmetric axes, using e.g., OffsetArrays. In JuliaImages we take the meaning of the coordinates literally in terms of the mathematics of convolution, so `psf[0, 0, 0]` is the "center" of the PSF.

**Comment by roflmaostc** [comment]
Ah, I see.
I'm not sure what steps should be done to do that? I'm not really familiar with JuliaImages internals...

**Comment by timholy** [comment]
It can be special-cased here. See how we handle the`"mri-stack.tif"` image.

**Comment by roflmaostc** [comment]
@johnnychen94 
Ah, I can remember that already last time we had a few issues for a new release :D

According to the documentation you need to create a new tag, right?

**Comment by johnnychen94** [comment]
Done

**Comment by timholy** [comment]
One problem: now when we change the axes on the PSF array, it's a breaking change and we have to release version 2 of this package.

**Comment by roflmaostc** [comment]
I'm still slightly confused what we actually need to change?
Isn't it?
```julia
basename(imagefile) == "mri-stack.tif" || basename(imagefile) == "simple_3d_ball.tif" || basename(imagefile) == "simple_3d_psf.tif"
```

**Comment by timholy** [comment]
Oh, wait, is it still not loadable?

```julia
julia> using TestImages

julia> img = testimage("simple_3d_psf.tif")
ERROR: ArgumentError: "simple_3d_psf.tif" not found in `TestImages.remotefiles`. Do you mean one of the following?
  * "resolution_test_512.tif"
Stacktrace:
 [1] full_imagename(filename::String)
   @ TestImages ~/.julia/packages/TestImages/g3u50/src/TestImages.jl:116
 [2] testimage(filename::String; download_only::Bool, ops::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ TestImages ~/.julia/packages/TestImages/g3u50/src/TestImages.jl:80
 [3] testimage(filename::String)
   @ TestImages ~/.julia/packages/TestImages/g3u50/src/TestImages.jl:80
 [4] top-level scope
   @ REPL[2]:1
```
If so, that's a bit of a relief, because we can fix the axes before this other problem. I have a draft in #93.

**Comment by johnnychen94** [comment]
Yes, #91 adds the new image into `gh-pages` branch, then I made a tag for that commit (also in `gh-pages` branch) to trigger the artifacts build CI, now we need to update the source codes in `master` branch.

**Comment by johnnychen94** [comment]
@roflmaostc will you work on this issue to make it loadable? The only thing special here is to make `testimage("simple_3d_psf.tif")[0, 0, i]` is the center point of the i-th slice. #93 gives a hint of what it could be done with OffsetArray.

Given that this package does not depend on ImageFiltering, we need to copy [`ImageFiltering.centered`](https://github.com/JuliaImages/ImageFiltering.jl/blob/19dcc5d74841e7be58231c99f001f29952aaeaaa/src/utils.jl#L1-L18) and use it here.

**Comment by roflmaostc** [comment]
Sorry, I saw the PR of @timholy and wasn't sure whether he'll finish it. 
Should I copy his lines and make a new PR?

**Comment by johnnychen94** [comment]
Yeah, I think it's better for you to make the PR since these two images are uploaded by you :P

**Comment by roflmaostc** [comment]
I'll try to get it done in the next few days :D

**Comment by timholy** [comment]
Yeah, I wasn't sure how to get the images so I wasn't sure of the size. That PR was basically to show you what I meant.
